name: social_app
description: "Discord"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core engine for all Firebase services
  firebase_core: ^4.2.1

  # Firebase Authentication (email/password login)
  firebase_auth: ^6.1.2

  # Cloud Firestore (real-time database for messages & profiles)
  cloud_firestore: ^6.1.0

  # Firebase Storage (for profile avatars)
  firebase_storage: ^13.0.4

  # Image Picker (select avatar image)
  image_picker: ^1.1.1

  # Provider for theme + state updates
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/boards/

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf